### ISSUE TITLE
"Https & Wss"

### ISSUE THREAD

**Issue by adamgoose** [hoxton-one/deepstream.io-website#7]
Currently your home page advertises Https & Wss capabilities. However, these protocols are not yet supported by Deepstream. See https://github.com/hoxton-one/deepstream.io/issues/19.

I believe that either this statement should be removed until issue 19 is resolved, and/or issue 19 should be made a top priority.

**Comment by yasserf** [comment]
SSL has now been implemented thanks to your PR. It hasn't yet been officially released however since we are looking to update the documentation first. Will make adding that our top priority.

**Comment by yasserf** [comment]
Cool, we added some documentation on how to enable it. Just released version 0.3.0! Looking forward to your feedback!

**Comment by WolframHempel** [comment]
Closed with 0.3.0. Thanks again for your feedback
