### ISSUE TITLE
Messages-URLs are broken

### ISSUE THREAD

**Issue by jwanglof** [hoxton-one/deepstream.io-website#8]
Below the 'Messages'-topic on http://deepstream.io/tutorials/permissioning.html

* **Text**: topic is a constant that defines what the message relates to, e.g. RECORD, EVENT, RPC, AUTH etc. Please find a full list of topics here
 * here points to: http://deepstream.io/docs/Constants.html#Topic
 * it shoud point to: http://deepstream.io/docs/constants.html#Topic

* **Text**: action is a constant that defines what should happen to the topic, e.g. 'CREATE_OR_READ', 'SUBSCRIBE', 'DELETE' etc. Please find a full list of actions here
 * here points to: http://deepstream.io/docs/Constants.html#Actions
 * it shoud point to: http://deepstream.io/docs/constants.html#Actions

**Comment by yasserf** [comment]
Many thanks for catching the issue!
